spring:
   datasource:
      url: jdbc:mysql://localhost:3306/blog
      username: yu
      password: 123
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      
logging:
   level:
      root: warn
      com.bigchickenleg.blog: info
   file: log/blog-pro.log

   
      

